# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftLearningDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftLearningDemo
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxSwiftExt', '~> 5'
end
